### ISSUE TITLE
keeps on crashing

### ISSUE THREAD

**Issue by master7720** [lambda-client/lambda-legacy#163]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LambdaMixinLoader (lambda-2.07.01.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 10/5/21 9:24 PM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access field net.minecraft.util.math.Vec3i.field_177962_a from class baritone.k
	at baritone.k.a(Unknown Source)
	at baritone.k.onTick(Unknown Source)
	at baritone.cf.a(Unknown Source)
	at baritone.cf$$Lambda$1136/130953249.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.cf.onTick(Unknown Source)
	at net.minecraft.client.Minecraft.handler$runTick$zdl000(Minecraft.java)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1755)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at baritone.k.a(Unknown Source)
	at baritone.k.onTick(Unknown Source)
	at baritone.cf.a(Unknown Source)
	at baritone.cf$$Lambda$1136/130953249.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.cf.onTick(Unknown Source)
	at net.minecraft.client.Minecraft.handler$runTick$zdl000(Minecraft.java)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['PreparedSystem32'/168, l='MpServer', x=221.39, y=68.00, z=352.18]]
	Chunk stats: MultiplayerChunkCache: 164, 164
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (220,64,252), Chunk: (at 12,4,12 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 409585 game time, 52095 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 18 total; [EntityParrot['Parrot'/96, l='MpServer', x=265.85, y=64.00, z=326.72], EntityPlayerSP['PreparedSystem32'/168, l='MpServer', x=221.39, y=68.00, z=352.18], EntityOcelot['Ocelot'/97, l='MpServer', x=268.50, y=67.00, z=356.50], EntitySheep['Sheep'/74, l='MpServer', x=229.23, y=69.00, z=279.31], EntityItem['item.tile.sandStone.default'/75, l='MpServer', x=228.13, y=60.00, z=349.46], EntityBat['Bat'/76, l='MpServer', x=238.17, y=17.05, z=401.84], EntitySheep['Sheep'/50, l='MpServer', x=156.40, y=73.92, z=280.45], EntityOcelot['Ocelot'/51, l='MpServer', x=146.50, y=72.00, z=283.50], EntityBat['Bat'/84, l='MpServer', x=247.21, y=15.93, z=395.09], EntitySheep['Sheep'/54, l='MpServer', x=165.77, y=70.00, z=279.49], EntityCow['Cow'/55, l='MpServer', x=160.49, y=74.00, z=274.82], EntityOcelot['Ocelot'/56, l='MpServer', x=175.39, y=75.00, z=320.19], EntitySheep['Sheep'/58, l='MpServer', x=182.79, y=69.00, z=278.56], EntityBat['Bat'/59, l='MpServer', x=191.60, y=18.00, z=410.84], EntitySheep['Sheep'/93, l='MpServer', x=267.55, y=64.00, z=327.45], EntityOcelot['Ocelot'/62, l='MpServer', x=201.50, y=67.00, z=292.50], EntityParrot['Parrot'/94, l='MpServer', x=265.44, y=65.00, z=327.18], EntityParrot['Parrot'/95, l='MpServer', x=268.03, y=66.00, z=327.75]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 314686096 bytes (300 MB) / 738197504 bytes (704 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xverify:none
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature                                |
	|:------ |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2855.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2855 | forge-1.12.2-14.23.5.2855.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | lambda    | 2.07.01      | lambda-2.07.01.jar            | None                                     |

	Loaded coremods (and transformers): 
LambdaMixinLoader (lambda-2.07.01.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.5058' Renderer: 'Intel(R) HD Graphics 5500'
	Launched Version: 1.12.2-forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 5500 GL version 4.4.0 - Build 20.19.15.5058, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz

**Comment by NepNep21** [comment]
Remove -noverify from your arguments

**Comment by scorbett123** [comment]
It's actually -Xverify:none, but yea, remove it.
