### ISSUE TITLE
Client crashes whenever I load a world

### ISSUE THREAD

**Issue by middleclicker** [lambda-client/lambda-legacy#166]
**Describe the bug**
Client crashes whenever I open a world.

**To Reproduce**
Open the client and load into a world (or server).

**Expected behavior**
I expected the client to not crash...

**Debug info**
```
java.lang.IllegalAccessError: tried to access field net.minecraft.util.math.Vec3i.field_177962_a from class baritone.k
	at baritone.k.a(Unknown Source)
	at baritone.k.onTick(Unknown Source)
	at baritone.cf.a(Unknown Source)
	at baritone.cf$$Lambda$1157/1695696731.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.cf.onTick(Unknown Source)
	at net.minecraft.client.Minecraft.handler$runTick$zdl000(Minecraft.java)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1755)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Additional context / media**

**Comment by ToxicAven** [comment]
Disable -noverify and stop pirating software.
