### ISSUE TITLE
Game crash on Hitting tab

### ISSUE THREAD

**Issue by joennespreuwers** [lambda-client/lambda-legacy#231]
**Describe the bug**
Whenever I hit the tab key ingame, my client crashes with the error `The game crashed whilst unexpected error
Error: java.lang.IndexOutOfBoundsException: toIndex = 255
Exit Code: -1`

**To Reproduce**
Hit tab

**Expected behavior**
Show the goddamn tab

**Crash report**
```---- Minecraft Crash Report ----

WARNING: coremods are present:
  WurstplusMixinLoader (WurstPlusTwo.jar)
  LambdaCoreMod (lambda-3.0.1.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 1/26/22 2:56 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: toIndex = 255
	at java.util.ArrayList.subListRangeCheck(ArrayList.java:1004)
	at java.util.ArrayList.subList(ArrayList.java:996)
	at net.minecraft.client.gui.GuiPlayerTabOverlay.redirect$subListHook$zfa000(SourceFile:1019)
	at net.minecraft.client.gui.GuiPlayerTabOverlay.func_175249_a(SourceFile:83)
	at net.minecraftforge.client.GuiIngameForge.renderPlayerList(GuiIngameForge.java:844)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:201)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1098)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.subListRangeCheck(ArrayList.java:1004)
	at java.util.ArrayList.subList(ArrayList.java:996)
	at net.minecraft.client.gui.GuiPlayerTabOverlay.redirect$subListHook$zfa000(SourceFile:1019)
	at net.minecraft.client.gui.GuiPlayerTabOverlay.func_175249_a(SourceFile:83)
	at net.minecraftforge.client.GuiIngameForge.renderPlayerList(GuiIngameForge.java:844)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:201)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['MrSprew'/382399, l='MpServer', x=-229.44, y=256.75, z=-279.36]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (72,64,8), Chunk: (at 8,4,8 in 4,0; contains blocks 64,0,0 to 79,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 78184 game time, 1373529275 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 3 total; [EntityWither['Discord.gg/Ybwqf8g95S Renegade!'/4945039, l='MpServer', x=-222.50, y=2.17, z=-256.45], EntityWitherSkull['entity.WitherSkull.name'/4948310, l='MpServer', x=-255.94, y=17.43, z=-285.28], EntityPlayerSP['MrSprew'/382399, l='MpServer', x=-229.44, y=256.75, z=-279.36]]
	Retry entities: 0 total; []
	Server brand: Waterfall <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 376648592 bytes (359 MB) / 1241513984 bytes (1184 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature                                |
	|:------ |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | lambda    | 3.0.1        | lambda-3.0.1.jar              | None                                     |
	| LCHIJA | wurstplus | 1.0          | WurstPlusTwo.jar              | None                                     |

	Loaded coremods (and transformers): 
WurstplusMixinLoader (WurstPlusTwo.jar)
  
LambdaCoreMod (lambda-3.0.1.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 511.23' Renderer: 'NVIDIA GeForce RTX 2070 Super/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 2070 Super/PCIe/SSE2 GL version 4.6.0 NVIDIA 511.23, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Excessive_Force_Anarchy_Pack_1.0.0.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
```

**Comment by ToxicAven** [comment]
This is a known issue with Wurst+2. Why are you even using a trashy, buggy and outdated client?

**Comment by huddy987** [comment]
Try again with Wurst+2 removed. If it still happens we can re-open this issue. Otherwise, this seems like an issue with Wurst+2.

**Comment by ToxicAven** [comment]
> Try again with Wurst+2 removed. If it still happens we can re-open this issue. Otherwise, this seems like an issue with Wurst+2.

This *is* an issue with Wurst+2, and it has been known for a very long time.

**Comment by a-a-afk** [comment]
https://github.com/colmalle/WurstPlusTwo-fix
