### ISSUE TITLE
Error when trying to run client in IDE.

### ISSUE THREAD

**Issue by ABeater** [lambda-client/lambda-legacy#329]
I wanted to try If I could add Minecart chests to the stash logger but when trying to execute "run client" (with --scan option) in the IDE I get this Error:

```
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.Minecraft.readImageToBuffer(Minecraft.java:841)
	at net.minecraft.client.Minecraft.setWindowIcon(Minecraft.java:680)
	at net.minecraft.client.Minecraft.init(Minecraft.java:456)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.legacydev.Main.start(Main.java:86)
	at net.minecraftforge.legacydev.MainClient.main(MainClient.java:29)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_332, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 274802376 bytes (262 MB) / 668991488 bytes (638 MB) up to 3808428032 bytes (3632 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
LambdaCoreMod (unknown)
  
	Launched Version: ${MC_VERSION}
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
[12:19:55] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\l0calh0st\lambda\run\.\crash-reports\crash-2022-06-09_12.19.55-client.txt

> Task :runClient FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9.1/userguide/command_line_interface.html#sec:command_line_warnings
12 actionable tasks: 11 executed, 1 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runClient'.
> Process 'command 'C:\Program Files\Eclipse Adoptium\jdk-8.0.332.9-hotspot\bin\java.exe'' finished with non-zero exit value -1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 25s

```

I tried looking for "java.exe finished with non-zero exit value -1"  but didnt find anything useful....

**Comment by mmvanheusden** [comment]
try it again for some reason the first time you run it exits with error
code -1

**Comment by ABeater** [comment]
That doesn't seem to fix it.

Maybe it's important to mention that I don't seem to have this option shown in the tutorial:
`lambda > Tasks > build > runClient`

but did the run through this: `lambda > Tasks > fg_runs > runClient`

**Comment by mmvanheusden** [comment]
> That doesn't seem to fix it.
> 
> Maybe it's important to mention that I don't seem to have this option shown in the tutorial:
> `lambda > Tasks > build > runClient`
> 
> but did the run through this: `lambda > Tasks > fg_runs > runClient`

have you ran the setup script first? also try restarting your pc (yes sometimes that fixes issues with gradle for me)

**Comment by ABeater** [comment]
I think it works now. I would assume it's supposed to open Minecraft when I click "run client"? At least I don't see an Error anymore.
