### ISSUE TITLE
Crash for no reason

### ISSUE THREAD

**Issue by Cosn1c** [lambda-client/lambda-legacy#482]
Minecraft just crash even with no mods. I use forge 14.23.5.2860 and java 8

Steps to reproduce the bug
1. Open minecraft
2. Wait..
3. Crash

Crash report : 
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Lambda (lambda)
Caused by: java.lang.ExceptionInInitializerError
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(Unknown Source)
	at sun.reflect.ReflectionFactory.newFieldAccessor(Unknown Source)
	at java.lang.reflect.Field.acquireFieldAccessor(Unknown Source)
	at java.lang.reflect.Field.getFieldAccessor(Unknown Source)
	at java.lang.reflect.Field.get(Unknown Source)
	at com.lambda.client.commons.utils.ClassUtils.getInstance(ClassUtils.kt:27)
	at com.lambda.client.module.ModuleManager.load0(ModuleManager.kt:43)
	at com.lambda.client.module.ModuleManager.load0(ModuleManager.kt:16)
	at com.lambda.client.AsyncLoader$DefaultImpls.load(Loader.kt:49)
	at com.lambda.client.module.ModuleManager.load(ModuleManager.kt:16)
	at com.lambda.client.LoaderWrapper$loadAll$1.invokeSuspend(Loader.kt:32)
	at com.lambda.shadow.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at com.lambda.shadow.kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.lambda.shadow.kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at com.lambda.shadow.kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at com.lambda.shadow.kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at com.lambda.shadow.kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at com.lambda.shadow.kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at com.lambda.shadow.kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.lambda.client.LoaderWrapper.loadAll(Loader.kt:31)
	at com.lambda.client.LambdaMod.init(LambdaMod.kt:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Failed to compile shader: /assets/shaders/menu/clouds.fsh
	at com.lambda.client.module.modules.client.MenuShader$ShaderProgram.createShader(MenuShader.kt:127)
	at com.lambda.client.module.modules.client.MenuShader$ShaderProgram.<init>(MenuShader.kt:89)
	at com.lambda.client.module.modules.client.MenuShader.getShader(MenuShader.kt:77)
	at com.lambda.client.module.modules.client.MenuShader.<clinit>(MenuShader.kt:56)
	... 63 more

**Comment by ToxicAven** [comment]
What hardware and graphics drivers are you using?

**Comment by ToxicReno** [comment]
this happen for me to

**Comment by Cosn1c** [comment]
Idk i use pojav

**Comment by ToxicAven** [comment]
> this happen for me to

Post your system information.

**Comment by ToxicAven** [comment]
Pojav is unsupported using lambda.

**Comment by ToxicReno** [comment]
> > this happen for me to
> 
> Post your system information.

Device name	RenoComputer
Processor	AMD Ryzen 5 5500U with Radeon Graphics            2.10 GHz
Installed RAM	12.0 GB (11.3 GB usable)
Device ID	A680AA78-8EE5-4417-8474-CA60A58AC389
Product ID	00342-21979-06555-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
