### ISSUE TITLE
Pojavlauncher crash

### ISSUE THREAD

**Issue by Nevada666** [lambda-client/lambda-legacy#531]
when I decided to update the lambda client , I ran into a problem with pojavlauncher crashing.  the previous version of the lambda works.
If you run lambda 3.3.0 in pojavlauncher, you can see crash and error -1. 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LambdaCoreMod (lambda-3.3.0.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 5/12/23 10:40 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Lambda (lambda)
Caused by: java.lang.ExceptionInInitializerError
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(Unknown Source)
	at sun.reflect.ReflectionFactory.newFieldAccessor(Unknown Source)
	at java.lang.reflect.Field.acquireFieldAccessor(Unknown Source)
	at java.lang.reflect.Field.getFieldAccessor(Unknown Source)
	at java.lang.reflect.Field.get(Unknown Source)
	at com.lambda.client.commons.utils.ClassUtils.getInstance(ClassUtils.kt:27)
	at com.lambda.client.module.ModuleManager.load0(ModuleManager.kt:43)
	at com.lambda.client.module.ModuleManager.load0(ModuleManager.kt:16)
	at com.lambda.client.AsyncLoader$DefaultImpls.load(Loader.kt:49)
	at com.lambda.client.module.ModuleManager.load(ModuleManager.kt:16)
	at com.lambda.client.LoaderWrapper$loadAll$1.invokeSuspend(Loader.kt:32)
	at com.lambda.shadow.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at com.lambda.shadow.kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.lambda.shadow.kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at com.lambda.shadow.kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at com.lambda.shadow.kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at com.lambda.shadow.kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at com.lambda.shadow.kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at com.lambda.shadow.kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.lambda.client.LoaderWrapper.loadAll(Loader.kt:31)
	at com.lambda.client.LambdaMod.init(LambdaMod.kt:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Failed to compile shader: /assets/shaders/menu/clouds.fsh
	at com.lambda.client.module.modules.client.MenuShader$ShaderProgram.createShader(MenuShader.kt:139)
	at com.lambda.client.module.modules.client.MenuShader$ShaderProgram.<init>(MenuShader.kt:101)
	at com.lambda.client.module.modules.client.MenuShader.getShader(MenuShader.kt:89)
	at com.lambda.client.module.modules.client.MenuShader.<clinit>(MenuShader.kt:58)
	... 63 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (aarch64) version Android-11
	Java Version: 1.8.0_372-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4326876408 bytes (4126 MB) / 5313658880 bytes (5067 MB) up to 5313658880 bytes (5067 MB)
	JVM Flags: 3 total; -Xms5210M -Xmx5210M -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version      | Source                        | Signature                                |
	|:----- |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHI  | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHI  | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHI  | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge     | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHE  | lambda    | 3.3.0        | lambda-3.3.0.jar              | None                                     |

	Loaded coremods (and transformers): 
LambdaCoreMod (lambda-3.3.0.jar)
  
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 7
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 gl4es wrapper 1.1.4
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8

**Comment by ToxicAven** [comment]
This might be possible to fix by disabling menushader if it detects incompatible OpenGL versions. We'll look into this as it may also be a general fix for older model computers as well.

**Comment by tiredElephant** [comment]
I got the exact same error on PojavLauncher both on my Tab S8 (Android 13/Snapdragon 8gen1) and my S20 (Android 13/SD 865)

**Comment by noone-git** [comment]
@Nevada666 @tiredElephant i disabled menushader on [my fork](https://github.com/maybelucid/lambda), it should work with pojav

**Comment by nikitadan4pi** [comment]
@maybelucid , your fork not work, and this cheat not work on all versions pojavlauncher. Kami blue 1.1 work, but bad. Plese, help!

**Comment by noone-git** [comment]
> @maybelucid , your fork not work, and this cheat not work on all versions pojavlauncher. Kami blue 1.1 work, but bad. Plese, help!

send me your log file. it works normally on my end

**Comment by nikitadan4pi** [comment]
The logs identical on first message

**Comment by noone-git** [comment]
> The logs identical on first message

yeah but i still need them for further information, im not a some kind of wizard that can magically guess your problem

**Comment by nikitadan4pi** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LambdaCoreMod (lambda-3.4.0.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 9/18/23 5:08 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Lambda (lambda)
Caused by: java.lang.ExceptionInInitializerError
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(Unknown Source)
	at sun.reflect.ReflectionFactory.newFieldAccessor(Unknown Source)
	at java.lang.reflect.Field.acquireFieldAccessor(Unknown Source)
	at java.lang.reflect.Field.getFieldAccessor(Unknown Source)
	at java.lang.reflect.Field.get(Unknown Source)
	at com.lambda.client.commons.utils.ClassUtils.getInstance(ClassUtils.kt:27)
	at com.lambda.client.module.ModuleManager.load0(ModuleManager.kt:43)
	at com.lambda.client.module.ModuleManager.load0(ModuleManager.kt:16)
	at com.lambda.client.AsyncLoader$DefaultImpls.load(Loader.kt:49)
	at com.lambda.client.module.ModuleManager.load(ModuleManager.kt:16)
	at com.lambda.client.LoaderWrapper$loadAll$1.invokeSuspend(Loader.kt:32)
	at com.lambda.shadow.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at com.lambda.shadow.kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.lambda.shadow.kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at com.lambda.shadow.kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at com.lambda.shadow.kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at com.lambda.shadow.kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at com.lambda.shadow.kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at com.lambda.shadow.kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.lambda.client.LoaderWrapper.loadAll(Loader.kt:31)
	at com.lambda.client.LambdaMod.init(LambdaMod.kt:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Failed to compile shader: /assets/shaders/menu/clouds.fsh
	at com.lambda.client.module.modules.client.MenuShader$ShaderProgram.createShader(MenuShader.kt:139)
	at com.lambda.client.module.modules.client.MenuShader$ShaderProgram.<init>(MenuShader.kt:101)
	at com.lambda.client.module.modules.client.MenuShader.getShader(MenuShader.kt:89)
	at com.lambda.client.module.modules.client.MenuShader.<clinit>(MenuShader.kt:58)
	... 63 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (aarch64) version Android-12
	Java Version: 1.8.0_372-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3157344848 bytes (3011 MB) / 4128768000 bytes (3937 MB) up to 4128768000 bytes (3937 MB)
	JVM Flags: 3 total; -Xms4060M -Xmx4060M -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version      | Source                        | Signature                                |
	|:----- |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHI  | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHI  | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHI  | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge     | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHE  | lambda    | 3.4.0        | lambda-3.4.0.jar              | None                                     |

	Loaded coremods (and transformers): 
LambdaCoreMod (lambda-3.4.0.jar)
  
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 18
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 gl4es wrapper 1.1.4
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8
Crash report

**Comment by noone-git** [comment]
> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present: LambdaCoreMod (lambda-3.4.0.jar) Contact their authors BEFORE contacting forge
> 
> // Surprise! Haha. Well, this is awkward.
> 
> Time: 9/18/23 5:08 PM Description: There was a severe problem during mod loading that has caused the game to fail
> 
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Lambda (lambda) Caused by: java.lang.ExceptionInInitializerError at sun.misc.Unsafe.ensureClassInitialized(Native Method) at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(Unknown Source) at sun.reflect.ReflectionFactory.newFieldAccessor(Unknown Source) at java.lang.reflect.Field.acquireFieldAccessor(Unknown Source) at java.lang.reflect.Field.getFieldAccessor(Unknown Source) at java.lang.reflect.Field.get(Unknown Source) at com.lambda.client.commons.utils.ClassUtils.getInstance(ClassUtils.kt:27) at com.lambda.client.module.ModuleManager.load0(ModuleManager.kt:43) at com.lambda.client.module.ModuleManager.load0(ModuleManager.kt:16) at com.lambda.client.AsyncLoader$DefaultImpls.load(Loader.kt:49) at com.lambda.client.module.ModuleManager.load(ModuleManager.kt:16) at com.lambda.client.LoaderWrapper$loadAll$1.invokeSuspend(Loader.kt:32) at com.lambda.shadow.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at com.lambda.shadow.kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108) at com.lambda.shadow.kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280) at com.lambda.shadow.kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) at com.lambda.shadow.kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) at com.lambda.shadow.kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) at com.lambda.shadow.kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) at com.lambda.shadow.kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) at com.lambda.client.LoaderWrapper.loadAll(Loader.kt:31) at com.lambda.client.LambdaMod.init(LambdaMod.kt:71) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) at com.google.common.eventbus.EventBus.post(EventBus.java:217) at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) at com.google.common.eventbus.EventBus.post(EventBus.java:217) at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749) at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336) at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535) at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) at net.minecraft.client.main.Main.main(SourceFile:123) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: java.lang.IllegalStateException: Failed to compile shader: /assets/shaders/menu/clouds.fsh at com.lambda.client.module.modules.client.MenuShader$ShaderProgram.createShader(MenuShader.kt:139) at com.lambda.client.module.modules.client.MenuShader$ShaderProgram.(MenuShader.kt:101) at com.lambda.client.module.modules.client.MenuShader.getShader(MenuShader.kt:89) at com.lambda.client.module.modules.client.MenuShader.(MenuShader.kt:58) ... 63 more
> 
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> -- System Details -- Details: Minecraft Version: 1.12.2 Operating System: Linux (aarch64) version Android-12 Java Version: 1.8.0_372-internal, Oracle Corporation Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 3157344848 bytes (3011 MB) / 4128768000 bytes (3937 MB) up to 4128768000 bytes (3937 MB) JVM Flags: 3 total; -Xms4060M -Xmx4060M -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0 FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 5 mods loaded, 5 mods active States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> ```
> | State | ID        | Version      | Source                        | Signature                                |
> |:----- |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
> | LCHI  | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
> | LCHI  | mcp       | 9.42         | minecraft.jar                 | None                                     |
> | LCHI  | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> | LCHI  | forge     | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> | LCHE  | lambda    | 3.4.0        | lambda-3.4.0.jar              | None                                     |
> 
> Loaded coremods (and transformers): 
> ```
> 
> LambdaCoreMod (lambda-3.4.0.jar)
> 
> ```
> OptiFine Version: OptiFine_1.12.2_HD_U_G5
> OptiFine Build: 20210124-142939
> Render Distance Chunks: 18
> Mipmaps: 0
> Anisotropic Filtering: 1
> Antialiasing: 0
> Multitexture: false
> Shaders: null
> OpenGlVersion: 2.1 gl4es wrapper 1.1.4
> OpenGlRenderer: GL4ES wrapper
> OpenGlVendor: ptitSeb
> CpuCount: 8
> ```
> 
> Crash report

are you sure you downloaded the build from [github actions](https://github.com/maybelucid/lambda/actions/runs/5989125052)?
cause it works just fine for me
![Screenshot_20230918-200630_PojavLauncher (Minecraft_ Java Edition for Android)](https://github.com/lambda-client/lambda/assets/139885555/5081c542-16f1-41f0-b3a6-071131b0ff01)
or perhaps youre running a very very old version of pojav?

**Comment by ToxicAven** [comment]
The problem is their phone does not support a new enough version of OpenGL to compile the menushader.

**Comment by nikitadan4pi** [comment]
I run it on last google play version.

**Comment by nikitadan4pi** [comment]
I check actions, but, how I can download working version, if I use phone? Can you send guide plese?

**Comment by nikitadan4pi** [comment]
Yees! It's working!
![Uploading Screenshot_20230918-212345.png…]()

**Comment by nikitadan4pi** [comment]
It work, thanks 
![Screenshot_20230918-212345](https://github.com/lambda-client/lambda/assets/85764647/12f3e5a5-3c45-4826-b7a9-7f35ccaa6908)

**Comment by noone-git** [comment]
> The problem is their phone does not support a new enough version of OpenGL to compile the menushader.

i dont think it causes that, i deleted every menushader related code ~~in a very messy way~~ so it should work with old opengl version, they prolly downloaded the build from the download button on the README.md which redirects to this repo
