### ISSUE TITLE
doesn't work on pojav 

### ISSUE THREAD

**Issue by htung2706** [lambda-client/lambda-legacy#590]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LambdaCoreMod (lambda-3.4.0.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 5/16/24 2:16 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Lambda (lambda)
Caused by: java.lang.ExceptionInInitializerError
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(Unknown Source)
	at sun.reflect.ReflectionFactory.newFieldAccessor(Unknown Source)
	at java.lang.reflect.Field.acquireFieldAccessor(Unknown Source)
	at java.lang.reflect.Field.getFieldAccessor(Unknown Source)
	at java.lang.reflect.Field.get(Unknown Source)
	at com.lambda.client.commons.utils.ClassUtils.getInstance(ClassUtils.kt:27)
	at com.lambda.client.module.ModuleManager.load0(ModuleManager.kt:43)
	at com.lambda.client.module.ModuleManager.load0(ModuleManager.kt:16)
	at com.lambda.client.AsyncLoader$DefaultImpls.load(Loader.kt:49)
	at com.lambda.client.module.ModuleManager.load(ModuleManager.kt:16)
	at com.lambda.client.LoaderWrapper$loadAll$1.invokeSuspend(Loader.kt:32)
	at com.lambda.shadow.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at com.lambda.shadow.kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.lambda.shadow.kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at com.lambda.shadow.kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at com.lambda.shadow.kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at com.lambda.shadow.kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at com.lambda.shadow.kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at com.lambda.shadow.kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.lambda.client.LoaderWrapper.loadAll(Loader.kt:31)
	at com.lambda.client.LambdaMod.init(LambdaMod.kt:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Shader failed to link
	at com.lambda.client.module.modules.client.MenuShader$ShaderProgram.<init>(MenuShader.kt:112)
	at com.lambda.client.module.modules.client.MenuShader.getShader(MenuShader.kt:89)
	at com.lambda.client.module.modules.client.MenuShader.<clinit>(MenuShader.kt:58)
	... 63 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (aarch64) version Android-13
	Java Version: 1.8.0_392-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 717040064 bytes (683 MB) / 1140326400 bytes (1087 MB) up to 1140326400 bytes (1087 MB)
	JVM Flags: 3 total; -Xms1148M -Xmx1148M -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version      | Source                        | Signature                                |
	|:----- |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHI  | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHI  | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHI  | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge     | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHE  | lambda    | 3.4.0        | lambda-3.4.0.jar              | None                                     |

	Loaded coremods (and transformers): 
LambdaCoreMod (lambda-3.4.0.jar)
  
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 gl4es wrapper 1.1.5
	OpenGlRenderer: Mali-G52
	OpenGlVendor: PojavLauncherTeam & ptitSeb
	CpuCount: 8

**Comment by RealmKebab** [comment]
dont use pojav you silly goose

**Comment by bendixd12** [comment]
its not meant for pojav you retarded

**Comment by based0000** [comment]
`Caused by: java.lang.IllegalStateException: Shader failed to link`
It's most likely an issue on pojav's side from their way of handling shaders, not lambda. If they won't fix it, or you want a simpler fix for the time being, try a more simple client that doesn't do anything with shaders. AFAIK wurst doesn't, so it might work.

EDIT: Considering the line `OpenGlVersion: 2.1 gl4es wrapper 1.1.5` it's probably some opengl version/extension issue.

**Comment by based0000** [comment]
also: duplicate of #531, check that issue for the fix.
